Fix deprecations
amboss-mededu/php-symfony1 pull request #3
Opened 2020-12-17 13:01 UTC by terdia

public static function isPathAbsolute($path)
  {
    if ($path{0} === '/' || $path{0} === '\\' ||
        (strlen($path) > 3 && ctype_alpha($path{0}) &&
         $path{1} === ':' &&
         ($path{2} === '\\' || $path{2} === '/')
        )
       )
    {
      return true;
    }

    return false;
  }
Causes deprecation warning:

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/vendor/lexpress/symfony1/lib/util/sfFinder.class.php on line 586

$this->getParameters = get_magic_quotes_gpc() ? sfToolkit::stripslashesDeep($_GET) : $_GET;
Deprecated: Function get_magic_quotes_gpc() is deprecated in /var/www/vendor/lexpress/symfony1/lib/request/sfWebRequest.class.php on line 78

2021-05-18 07:35 UTC, obukhov requested changes

2021-05-18 07:37 UTC, obukhov commented on lib/request/sfWebRequest.class.php
> +    }
Why wouldn't you keep it in PSR codestyle?

```
        if (version_compare(PHP_VERSION, '5.4.0-dev', '<') && get_magic_quotes_gpc()) {
            $this->postParameters = sfToolkit::stripslashesDeep($postParameters);
        } else {
            $this->postParameters = $postParameters;
        }
```

2021-05-18 08:01 UTC, terdia commented on lib/request/sfWebRequest.class.php
> +    if (version_compare(PHP_VERSION, '5.4.0-dev', '<') && get_magic_quotes_gpc())
Nope, that is for backward compatibility, from version `5.1.4` will be handled in else block.

2021-05-18 08:28 UTC, terdia commented on lib/form/sfForm.class.php
> +
`$this->validatorSchema` was used in line 947 before it was initialized, this code `$this->validatorSchema[self::$CSRFFieldName]` tries to access a key in `validatorSchema` the usage is triggered by `$this->setDefaults($defaults)` which calls the function `$this->isCSRFProtected()` this resulted in an exception trying to access array offset on value of type null

https://medicuja.slack.com/files/USCHJ5J22/F01V9N215KL/screenshot_2021-04-23_at_17.26.09.png?origin_team=T04FP177A&origin_channel=DSG3YR10W

2021-05-18 08:30 UTC, terdia commented on lib/form/sfForm.class.php
> +
![Screenshot 2021-05-18 at 10 29 56](https://user-images.githubusercontent.com/4749721/118618518-ff9e4400-b7c3-11eb-925a-ebe5552b8e47.png)

2021-05-18 09:45 UTC, obukhov commented on lib/request/sfWebRequest.class.php
> +    if (version_compare(PHP_VERSION, '5.4.0-dev', '<') && get_magic_quotes_gpc())
Maybe can you explain it in a little bit more detail? The only function behavior change I see here https://www.php.net/manual/en/function.get-magic-quotes-gpc.php is that this function was declared deprecated in 7.4 (probably started always returning false in the same version). 
Can you point me to information about changes in 5.4.0 and 5.1.4?

Does that let's say the PHP version is 5.6 and get_magic_quotes_gpc is enabled. Does that mean that sfToolkit::stripslashesDeep is still needed?

2021-05-18 09:46 UTC, obukhov commented on lib/request/sfWebRequest.class.php
> +    }
Oh sorry, that lead to a lot of unrelated changes, I see symfony1 has its own code style.
Would you mind reverting it?

2021-05-18 10:03 UTC, obukhov commented
Sorry for brining this idea a bit late, but why wouldn't we just pull original version of framework?

They seem to have introduced couple of improvements, including PHP 7.4 compatibilities and security fixes:

![image](https://user-images.githubusercontent.com/1958182/118632710-f9fb2b00-b7d0-11eb-88bf-52fc3b7bd609.png)


Our changes are not that big so maybe we can submit them to the upstream?
![image](https://user-images.githubusercontent.com/1958182/118632322-95d86700-b7d0-11eb-9f5b-58e4c955e7f4.png)

2021-05-18 10:10 UTC, terdia commented
> Sorry for brining this idea a bit late, but why wouldn't we just pull original version of framework?
> 
> They seem to have introduced couple of improvements, including PHP 7.4 compatibilities and security fixes:
> 
> ![image](https://user-images.githubusercontent.com/1958182/118632710-f9fb2b00-b7d0-11eb-88bf-52fc3b7bd609.png)
> 
> Our changes are not that big so maybe we can submit them to the upstream?
> ![image](https://user-images.githubusercontent.com/1958182/118632322-95d86700-b7d0-11eb-9f5b-58e4c955e7f4.png)

Good idea, we can try it and maybe open a pull request for https://github.com/amboss-mededu/php-symfony1/pull/3/commits/3294631e1c958da2dd9f27b2ffec0584f5e3078b

2021-05-28 15:11 UTC, terdia commented
closed in favor of: https://github.com/amboss-mededu/php-symfony1/pull/4

2021-05-28 15:11 UTC, closed without merging